### ISSUE TITLE
is it working.?

### ISSUE THREAD

**Issue by janbildsoehansen** [Cyclenerd/Latrine#1]
can i use this on a website just to show two cars running this app..??

hope you will help best regards Jan

**Comment by Cyclenerd** [comment]
Yes, but not both in one map. Check out my new project: https://livetracking.io

**Comment by janbildsoehansen** [comment]
Looks crazy nice work :)

so i have to make two maps to show the two cars on a webpage.?

but having trouble setting it up i can do a bit html thats it dont know
much about perl or how to deploy it to the server this latrine script you
have made

best regards jan

**Comment by janbildsoehansen** [comment]
im getting this Not Found

The requested URL /latrine.pl was not found on this server.


all the time when i try to setup your script :(



2017-09-09 13:38 GMT+02:00 BILDSØE PRODUCTION <janbildsoehansen@gmail.com>:

> Looks crazy nice work :)
>
> so i have to make two maps to show the two cars on a webpage.?
>
> but having trouble setting it up i can do a bit html thats it dont know
> much about perl or how to deploy it to the server this latrine script you
> have made
>
> best regards jan
>
>
